### ISSUE TITLE
Found an redundant variable in updatedb.py

### ISSUE THREAD

**Issue by MikeLing** [mozilla/ouija#102]
Hey Joel, I found an useless [varibale](https://github.com/mozilla/ouija/blob/master/src/updatedb.py#L78) in updatedb.py. Do we need it? And we miss a quote in [this line](https://github.com/mozilla/ouija/blob/master/src/updatedb.py#L87), but I had fix it in my recent PR. Thank u ;)

**Comment by jmaher** [comment]
yes, please remove the variable, add the missing quote, and remove return_type=list from the new url.  The url also needs % (branch, results_set_id)
