### ISSUE TITLE
android testtype are being stored as full string with platform for taskcluster jobs

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#104]
we break things down into tuples of 3: platform, buildtype, testtype.

for something like android opt crashtest-4, we would have: android, opt, crashtest-4

for taskcluster jobs, we get platform, buildtype correct, but the testtype has: "[TC] Android 4.3 API15+ crashtest-4"

This should be parsed when we deal with taskcluster jobs, ideally this would match 100% with buildbot jobs, but have an extra field for the ci system, or some indicator in the platform of [TC].  Why we need to separate these is that the taskcluster stuff is run in parallel.

**Comment by MikeLing** [comment]
@jmaher I create a pr https://github.com/mozilla/ouija/pull/106 for this issue. 

>
This should be parsed when we deal with taskcluster jobs, ideally this would match 100% with buildbot jobs, but have an extra field for the ci system, or some indicator in the platform of [TC]. Why we need to separate these is that the taskcluster stuff is run in parallel.
>

is that mean we should store testtype from taskcluster like '[TC]reftest-2'? Does it broken anything  on ouija? Anyway, I think we only need seta table and jobnames endpoint when we interact with taskcluster. :)

**Comment by jmaher** [comment]
If we are not adding a 4th field to the data for buildbot / taskcluster,
then using (TC)reftest-2 seems very good.  When we remove the TC from the
name eventually, it will need to be manually updated in the seta history.

For taskcluster we do just need the seta table via an endpoint.  I don't
think we will need special name creation.  In order to populate the seta
table, we do need most of the existing system.

**Comment by jmaher** [comment]
I don't think there is anything left to do here.  We have added support for build_system_type and inside of updatedb.py we have fixed up the platform/buildtype-testtype annotations which are found in taskcluster test jobs.  I am going to close this out for now!
