### ISSUE TITLE
We need a more robust seta endpoint

### ISSUE THREAD

**Issue by MikeLing** [mozilla/ouija#107]
Hey @jmaher , I found this when I test my pr via different branch. I missing some arguments in the url but it still return me data. But it's absolutely not right. You can test them by:

http://alertmanager.allizom.org/data/setadetails/?date=2016-07-14&buildbot=1&bran

and 

http://alertmanager.allizom.org/data/setadetails/?date=2016-07-14&buildbot=1&branch='abcd' 

and 

http://alertmanager.allizom.org/data/setadetails/?date=2016-07-14&buildb

shouldn't why do something to verify it? Maybe 404? or just a {}?

**Comment by jmaher** [comment]
I will need to look on a computer tonight.  I suspect this is how we parse
the URL options, in this case if we don't understand it we ignore the
unknown or invalid name or value and use the default.

That could be seen in the server.py code for the specific API endpoint.

Thanks for testing this and asking about it. I will look in more detail
later.

**Comment by jmaher** [comment]
I believe we need to verify this, since this is an api that is used for
automation systems and cannot be randomly applied to other
branches/environments, lets ensure the branches and other input values
match a specific list.

Ideally an error like {"error": <message>} where <message> could describe
which parameter had an invalid value.

**Comment by MikeLing** [comment]
alright, i will work on this. BTW, I will move on after dustin land task id and reply me on bugzilla :)

> 在 2016年7月18日，上午11:58，Joel Maher <notifications@github.com> 写道：
> 
> I believe we need to verify this, since this is an api that is used for
> automation systems and cannot be randomly applied to other
> branches/environments, lets ensure the branches and other input values
> match a specific list.
> 
> Ideally an error like {"error": <message>} where <message> could describe
> which parameter had an invalid value.
>

**Comment by jmaher** [comment]
I believe this is completed :)
