### ISSUE TITLE
Identify the 'new job' in seta

### ISSUE THREAD

**Issue by MikeLing** [mozilla/ouija#108]
After we make taskcluster schedule job based on seta, taskcluster will only care about high value jobs on the most of times. However, when a new job been added, it's almost impossible to get its result because it won't been run as high value job. So we must find a way to identify new job in seta and pass it to taskcluster.

**Comment by MikeLing** [comment]
I create a [PR]( https://github.com/mozilla/ouija/pull/110) for this issue.

**Comment by jmaher** [comment]
@MikeLing can we close this now?

**Comment by MikeLing** [comment]
Sure! :)
