### ISSUE TITLE
ROOT_DIR is used to find runnablejobs.json and src/preseed.json, this fails in apache

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#115]
when Apache is run as a service ROOT_DIR is blank, we need to possibly have a config file that specifies where to store the data files, or a backup if ROOT_DIR is ''.   This would have to be updated in many places in the code, but will make SETA more flexible.

**Comment by MikeLing** [comment]
@jmaher if we will switch our production version from alert manager to heroku soon(maybe I can make it happened within these two day), we could just ignore this issue because we no longer need apache on heroku. Does it make sense to you?

**Comment by jmaher** [comment]
yes, this seems reasonable- lets first get all the data in heroku, then see if all works well for a week

**Comment by jmaher** [comment]
overall, I think this has been edited enough that it isn't a problem.
