### ISSUE TITLE
Maybe we need a new (temp) endpoint to help us migrate data from alert manager to heroku 

### ISSUE THREAD

**Issue by MikeLing** [mozilla/ouija#118]
Hey @jmaher , I have been trying to dump mysql data and import it to postgresql on heroku. But it doesn't works well because right now the postgresql database we used on heroku is binding with sqlachemy which is hard to directly use data dump from non-sqlachemy binding database.

I propose to create a temp endpoint on alert manager which could return all data in testjobs table and we just query and store data on the heroku side. Anyway, we could remove that endpoint after migration been done and everything works well.

**Comment by jmaher** [comment]
I am more than happy to have this created- could we not do a mysqldump?  There will be a lot of data in the endpoint- possibly we will need to split it up by date or something.

**Comment by MikeLing** [comment]
https://github.com/mozilla/ouija/pull/122

**Comment by jmaher** [comment]
this is done, we can fine tune this over time.
