### ISSUE TITLE
seta-dev (master branch) src/updatedb.py uploads all data, instead it should only upload failure_classification=2 data

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#127]
SETA only uses data which has failure_classification=2, in that regard we should only be storing this data.

**Comment by jmaher** [comment]
@MikeLing do you want to do this?

**Comment by MikeLing** [comment]
ok, I will do it!

**Comment by MikeLing** [comment]
https://github.com/mozilla/ouija/pull/129
@jmaher r?

**Comment by jmaher** [comment]
this was merged in last week
