### ISSUE TITLE
I got a  'Access-Control-Allow-Origin' missing and 304 error when I run seta locally

### ISSUE THREAD

**Issue by MikeLing** [mozilla/ouija#152]
<img width="1267" alt="screen shot 2016-10-01 at 1 50 30 pm" src="https://cloud.githubusercontent.com/assets/2166227/19012121/5c81303a-87de-11e6-8868-529ca8a6b5b1.png">

Hi Joel @jmaher ,AS you can see, I got CORS header 'Access-Control-Allow-Origin' missing error in the web console and 304 error also in terminal. I'm not good at handle error like this, so please take a look at this issue. Otherwise, I will try to figure it out. Thank you :)

**Comment by jmaher** [comment]
odd, we shouldn't have this- to fix this we need to modify the web server to allow cors:
http://stackoverflow.com/questions/25594893/how-to-enable-cors-in-flask-and-heroku

outside of that, we should be running locally including all data- I have some local hacks to make that work- long term we should be able to support all local data and cors

**Comment by jmaher** [comment]
on this topic, the production instance seta.herokuapp.com has references to seta-dev.herokupapp.com via the api calls.  I see this when looking at the network calls from:
http://seta.herokuapp.com/seta.html

I believe we should find a way to reduce the pain points of the servers and make it configurable with a single place (even env var is ok)

**Comment by jmaher** [comment]
@MikeLing does the CORS fix you did recently fix this?

**Comment by MikeLing** [comment]
yep, let me close this :)
