### ISSUE TITLE
Communication strategy

### ISSUE THREAD

**Issue by armenzg** [mozilla/ouija#170]
In pulse_actions I start logging and I end logging using this logic:
https://github.com/mozilla/pulse_actions/blob/58ba015c2925e06f5b66310a83b3855fac7a20a3/pulse_actions/utils/log_util.py#L15

I then use my TC/S3 uploader to upload the log somewhere public (28 days):
https://github.com/mozilla/pulse_actions/blob/4a71ebb18d5379f4dd948563e005988a5d58d46f/pulse_actions/worker.py#L277-L281

**Comment by MikeLing** [comment]
@armenzg Is that about to store all log information into a local file? Do we need to worry about too many log data been stored and need us to manually deleted them? Hmm, one more thing is after we move seta into the treeherder, do we still need to do that?

Anyway, I think it's a good idea to apply into the seta and ouija :)

**Comment by armenzg** [comment]
I actually don't recall why I filed this issue.
I might have read in the code somewhere that we need a communication strategy.

In any case, I would not worry much about this since the rewrite will make this obsolete.

Please reopen if you still want this to be done but once the rewrite is completed we could take care of it then.
