### ISSUE TITLE
task name translation on ingestion is not untranslated on endpoint

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#175]
currently we translate task names during ingestion:
https://github.com/mozilla/ouija/blob/master/tools/update_runnablejobs.py#L233

These should be fixed in-tree (but apparently they are not), but either way, they need to be retranslated back so that we can serve proper data to taskcluster when it queries for low/high value jobs.

@MikeLing can you take this bug?  It should be a simple reversal of the .replace() methods when we are building the list of data points to return from the new SETA endpoint.

**Comment by MikeLing** [comment]
@jmaher Sure thing! I'm working on it :)

**Comment by jmaher** [comment]
this is fixed now!
