### ISSUE TITLE
We need fix flake8 error in ouija and support for it

### ISSUE THREAD

**Issue by MikeLing** [mozilla/ouija#86]
When I test our codebase by flake8, I got a lot of error and I think we should fix that:

src/server.py:18:1: E302 expected 2 blank lines, found 1
src/server.py:47:80: E501 line too long (97 > 79 characters)
src/server.py:69:80: E501 line too long (81 > 79 characters)
src/server.py:74:80: E501 line too long (81 > 79 characters)
src/server.py:121:80: E501 line too long (84 > 79 characters)
src/server.py:133:80: E501 line too long (205 > 79 characters)
src/server.py:137:80: E501 line too long (113 > 79 characters)
src/server.py:143:80: E501 line too long (89 > 79 characters)
src/server.py:144:80: E501 line too long (145 > 79 characters)
src/server.py:161:80: E501 line too long (81 > 79 characters)
src/server.py:228:5: E303 too many blank lines (2)
src/server.py:232:80: E501 line too long (80 > 79 characters)
src/server.py:270:21: E128 continuation line under-indented for visual indent
src/server.py:280:80: E501 line too long (80 > 79 characters)
src/server.py:296:80: E501 line too long (83 > 79 characters)
src/server.py:319:62: F821 undefined name 'result'
src/server.py:327:80: E501 line too long (80 > 79 characters)
src/server.py:367:1: E302 expected 2 blank lines, found 1
src/server.py:379:80: E501 line too long (93 > 79 characters)
src/server.py:393:80: E501 line too long (90 > 79 characters)
src/server.py:400:80: E501 line too long (88 > 79 characters)
src/server.py:424:45: E703 statement ends with a semicolon
src/server.py:426:80: E501 line too long (119 > 79 characters)
src/server.py:440:80: E501 line too long (99 > 79 characters)
src/server.py:518:5: E265 block comment should start with '# '
src/server.py:545:80: E501 line too long (98 > 79 characters)
src/server.py:549:80: E501 line too long (94 > 79 characters)
src/server.py:551:1: E302 expected 2 blank lines, found 1
src/server.py:560:23: E261 at least two spaces before inline comment
src/server.py:562:26: E261 at least two spaces before inline comment
src/server.py:563:22: E261 at least two spaces before inline comment
src/server.py:564:21: E261 at least two spaces before inline comment
src/server.py:578:1: E302 expected 2 blank lines, found 1
src/server.py:584:80: E501 line too long (80 > 79 characters)
src/server.py:605:80: E501 line too long (95 > 79 characters)
src/server.py:607:80: E501 line too long (87 > 79 characters)
src/server.py:609:80: E501 line too long (83 > 79 characters)
src/server.py:618:1: E302 expected 2 blank lines, found 1
src/server.py:622:1: E302 expected 2 blank lines, found 1
src/treecodes.py:2:18: E127 continuation line over-indented for visual indent
src/treecodes.py:42:80: E501 line too long (87 > 79 characters)
src/treecodes.py:43:80: E501 line too long (87 > 79 characters)
src/treecodes.py:44:80: E501 line too long (87 > 79 characters)
src/treecodes.py:45:80: E501 line too long (85 > 79 characters)
src/treecodes.py:46:80: E501 line too long (88 > 79 characters)
src/treecodes.py:47:80: E501 line too long (88 > 79 characters)
src/treecodes.py:48:80: E501 line too long (88 > 79 characters)
src/treecodes.py:49:80: E501 line too long (88 > 79 characters)
src/treecodes.py:166:80: E501 line too long (86 > 79 characters)
src/updatedb.py:2:1: F401 're' imported but unused
src/updatedb.py:52:1: E302 expected 2 blank lines, found 1
src/updatedb.py:65:80: E501 line too long (123 > 79 characters)
src/updatedb.py:68:1: E302 expected 2 blank lines, found 1
src/updatedb.py:72:80: E501 line too long (95 > 79 characters)
src/updatedb.py:78:80: E501 line too long (135 > 79 characters)
src/updatedb.py:81:1: E302 expected 2 blank lines, found 1
src/updatedb.py:86:80: E501 line too long (159 > 79 characters)
src/updatedb.py:100:13: F841 local variable 'push' is assigned to but never used
src/updatedb.py:104:1: E302 expected 2 blank lines, found 1
src/updatedb.py:107:80: E501 line too long (325 > 79 characters)
src/updatedb.py:118:1: E302 expected 2 blank lines, found 1
src/updatedb.py:130:5: E731 do not assign a lambda expression, use a def
src/updatedb.py:135:30: F841 local variable 'result' is assigned to but never used
src/updatedb.py:135:80: E501 line too long (120 > 79 characters)
src/updatedb.py:143:80: E501 line too long (85 > 79 characters)
src/updatedb.py:150:1: W293 blank line contains whitespace
src/updatedb.py:153:13: E265 block comment should start with '# '
src/updatedb.py:153:80: E501 line too long (94 > 79 characters)
src/updatedb.py:171:80: E501 line too long (142 > 79 characters)
src/updatedb.py:174:80: E501 line too long (100 > 79 characters)
src/updatedb.py:176:80: E501 line too long (97 > 79 characters)
src/updatedb.py:181:80: E501 line too long (147 > 79 characters)
src/updatedb.py:184:80: E501 line too long (132 > 79 characters)
src/updatedb.py:188:80: E501 line too long (82 > 79 characters)
src/updatedb.py:191:80: E501 line too long (107 > 79 characters)
src/updatedb.py:199:80: E501 line too long (86 > 79 characters)
src/updatedb.py:215:41: E502 the backslash is redundant between brackets
src/updatedb.py:216:57: E502 the backslash is redundant between brackets
src/updatedb.py:217:80: E501 line too long (89 > 79 characters)
src/updatedb.py:224:80: E501 line too long (88 > 79 characters)
src/updatedb.py:227:80: E501 line too long (126 > 79 characters)
src/updatedb.py:236:80: E501 line too long (81 > 79 characters)
src/updatedb.py:254:5: E265 block comment should start with '# '
src/updatedb.py:255:5: E265 block comment should start with '# '
src/updatedb.py:257:5: E265 block comment should start with '# '
src/updatedb.py:257:80: E501 line too long (84 > 79 characters)
src/updatedb.py:258:5: E265 block comment should start with '# '
src/updatedb.py:259:5: E265 block comment should start with '# '
src/updatedb.py:260:5: E265 block comment should start with '# '
src/updatedb.py:261:5: E265 block comment should start with '# '
src/updatedb.py:262:5: E265 block comment should start with '# '
src/updatedb.py:265:5: E265 block comment should start with '# '
src/updatedb.py:266:5: E265 block comment should start with '# '
tools/dailyjobs_query.py:4:1: F401 'sys' imported but unused
tools/dailyjobs_query.py:8:26: E128 continuation line under-indented for visual indent
tools/dailyjobs_query.py:9:26: E128 continuation line under-indented for visual indent
tools/dailyjobs_query.py:10:26: E128 continuation line under-indented for visual indent
tools/dailyjobs_query.py:21:32: E251 unexpected spaces around keyword / parameter equals
tools/dailyjobs_query.py:21:34: E251 unexpected spaces around keyword / parameter equals
tools/dailyjobs_query.py:21:80: E501 line too long (85 > 79 characters)
tools/dailyjobs_query.py:28:32: E251 unexpected spaces around keyword / parameter equals
tools/dailyjobs_query.py:28:34: E251 unexpected spaces around keyword / parameter equals
tools/dailyjobs_query.py:38:80: E501 line too long (91 > 79 characters)
tools/dailyjobs_query.py:38:91: E502 the backslash is redundant between brackets
tools/dailyjobs_query.py:40:80: E501 line too long (82 > 79 characters)
tools/dailyjobs_query.py:42:80: E501 line too long (81 > 79 characters)
tools/dailyjobs_query.py:64:15: E111 indentation is not a multiple of four
tools/dailyjobs_query.py:71:80: E501 line too long (138 > 79 characters)
tools/dailyjobs_query.py:88:80: E501 line too long (80 > 79 characters)
tools/dailyjobs_query.py:105:80: E501 line too long (94 > 79 characters)
tools/dailyjobs_query.py:107:80: E501 line too long (90 > 79 characters)
tools/dailyjobs_query.py:113:80: E501 line too long (82 > 79 characters)
tools/dailyjobs_query.py:118:80: E501 line too long (84 > 79 characters)
tools/dailyjobs_query.py:124:10: E111 indentation is not a multiple of four
tools/dailyjobs_query.py:125:10: E111 indentation is not a multiple of four
tools/dailyjobs_query.py:129:10: E111 indentation is not a multiple of four
tools/dailyjobs_query.py:130:10: E111 indentation is not a multiple of four
tools/emails.py:3:1: F401 'datetime' imported but unused
tools/emails.py:8:80: E501 line too long (89 > 79 characters)
tools/emails.py:9:80: E501 line too long (120 > 79 characters)
tools/emails.py:15:80: E501 line too long (104 > 79 characters)
tools/emails.py:17:80: E501 line too long (102 > 79 characters)
tools/emails.py:18:80: E501 line too long (100 > 79 characters)
tools/failures.py:13:1: E302 expected 2 blank lines, found 1
tools/failures.py:20:80: E501 line too long (145 > 79 characters)
tools/failures.py:22:80: E501 line too long (82 > 79 characters)
tools/failures.py:32:80: E501 line too long (114 > 79 characters)
tools/failures.py:41:80: E501 line too long (122 > 79 characters)
tools/failures.py:48:80: E501 line too long (114 > 79 characters)
tools/failures.py:50:80: E501 line too long (140 > 79 characters)
tools/failures.py:58:80: E501 line too long (130 > 79 characters)
tools/failures.py:124:26: E128 continuation line under-indented for visual indent
tools/failures.py:125:26: E128 continuation line under-indented for visual indent
tools/failures.py:126:26: E128 continuation line under-indented for visual indent
tools/failures.py:144:80: E501 line too long (83 > 79 characters)
tools/failures.py:147:80: E501 line too long (90 > 79 characters)
tools/failures.py:176:80: E501 line too long (113 > 79 characters)
tools/failures.py:220:80: E501 line too long (84 > 79 characters)
tools/failures.py:230:17: E261 at least two spaces before inline comment
tools/failures.py:233:80: E501 line too long (94 > 79 characters)
tools/failures.py:235:80: E501 line too long (94 > 79 characters)
tools/failures.py:237:80: E501 line too long (83 > 79 characters)
tools/failures.py:243:9: E265 block comment should start with '# '
tools/failures.py:259:80: E501 line too long (85 > 79 characters)
tools/failures.py:267:80: E501 line too long (83 > 79 characters)
tools/failures.py:271:80: E501 line too long (88 > 79 characters)
tools/failures.py:272:25: E128 continuation line under-indented for visual indent
tools/seta.py:8:80: E501 line too long (82 > 79 characters)
tools/seta.py:47:80: E501 line too long (124 > 79 characters)
tools/seta.py:81:1: E302 expected 2 blank lines, found 1
tools/seta.py:96:13: F841 local variable 'revision_list' is assigned to but never used
tools/seta.py:106:1: E302 expected 2 blank lines, found 1
tools/seta.py:110:23: E225 missing whitespace around operator
tools/seta.py:122:67: F821 undefined name 'master_root_cause'
tools/seta.py:122:80: E501 line too long (84 > 79 characters)
tools/seta.py:124:80: E501 line too long (88 > 79 characters)
tools/seta.py:151:23: E225 missing whitespace around operator
tools/seta.py:154:80: E501 line too long (80 > 79 characters)
tools/seta.py:158:80: E501 line too long (84 > 79 characters)
tools/seta.py:160:80: E501 line too long (88 > 79 characters)

@jmaher do you agree with it? I will commit a pr with tox supporting and error fixing :)

**Comment by jmaher** [comment]
Yes, I think we should fix this up- please go ahead and make this pass
flake8!

**Comment by MikeLing** [comment]
We could close this issue now :)
