### ISSUE TITLE
dailyjobs table is never pruned, we should prune data >180 days old

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#95]
in tools/dailyjobs_query.py we add information to the dailyjobs table about information of our current job load, we don't need this data forever, so lets make sure to delete old data when adding new.  we use the dashboard: http://alertmanager.allizom.org/dailyjobs.html, to track the effectiveness of SETA.

@MikeLing, this should be another optimization for the SETA toolchain.

**Comment by jmaher** [comment]
I believe we already do this for the old seta data, correct?

**Comment by MikeLing** [comment]
@jmaher  yep, maybe we could close this issue now :). Thank you Joel

**Comment by jmaher** [comment]
thanks for reminding me!
