### ISSUE TITLE
missing runnablejobs.json file on first run 

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#96]
ubuntu@ouija:~/ouija$ python src/server.py 
Traceback (most recent call last):
  File "src/server.py", line 18, in <module>
    JOBSDATA = jobtypes.Treecodes()
  File "/usr/local/lib/python2.7/dist-packages/ouija-0.0.0-py2.7.egg/src/jobtypes.py", line 53, in __init__
    with open(os.getcwd() + '/runnablejobs.json') as data:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/ouija/runnablejobs.json'
ubuntu@ouija:~/ouija$ 

@MikeLing can you take a look at this?

**Comment by MikeLing** [comment]
Hey @jmaher , I just create a PR for this issue https://github.com/mozilla/ouija/pull/100 r? Thank you

**Comment by MikeLing** [comment]
@jmaher Maybe we could close this and https://github.com/mozilla/ouija/issues/97 and https://github.com/mozilla/ouija/issues/98, also https://github.com/mozilla/ouija/issues/102 :)

**Comment by jmaher** [comment]
great, thanks for mentioning these!
