### ISSUE TITLE
failures.py fails with a datetime missing attribute of time_tuple

### ISSUE THREAD

**Issue by jmaher** [mozilla/ouija#97]
ubuntu@ouija:~/ouija/tools$ python failures.py 
Traceback (most recent call last):
  File "failures.py", line 328, in <module>
    update_runnableapi()
  File "failures.py", line 295, in update_runnableapi
    time_tuple = datetime.datetime.strptime(expires, "%Y-%m-%d").time_tuple()
AttributeError: 'datetime.datetime' object has no attribute 'time_tuple'
ubuntu@ouija:~/ouija/tools$ 

@MikeLing possibly I am doing something incorrect?

**Comment by jmaher** [comment]
doing time_tuple = time.strptime(expires, "%Y-%m-%d") works for me.

**Comment by MikeLing** [comment]
I fix it in https://github.com/mozilla/ouija/pull/99/files#diff-9d03adf43d3a159d0c625dcf10c6d4ccR295 here. Thank you for finding this. I should retest it after I change variable name.
